[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
crossterm = "0.27.0"
derive_more = "0.99.18"
visibility = "0.1.0"
neotext = { path = "../.." }
[features]
testing = []

